### ISSUE TITLE
All columns are assumed as type string

### ISSUE THREAD

**Issue by ipsycodex** [JudeOchalifu/Android-Device-SQLite-Viewer#1]
At Line 1146 we are considering all columns as string, this will give Exception. You can ammend that using following code.

String value = null;
                switch (c3.getType(j)) {
                    case Cursor.FIELD_TYPE_INTEGER:
                        value = String.valueOf(c3.getInt(j));
                        break;
                    case Cursor.FIELD_TYPE_FLOAT:
                        value = String.valueOf(c3.getFloat(j));
                        break;
                    case Cursor.FIELD_TYPE_STRING:
                        value = c3.getString(j);
                        break;
                }
columsView.setText("" + value);

**Comment by JudeOchalifu** [comment]
Thanks abhpatidar
